#
#   This is the core configuration for a configuration service.  There are two examples here:
#
#       -  A configuration service which completely loads the configuration for the services
#          from the local file server of the config service.  This should only be used for
#          demonstration purposes or for a small application with a limited number of services.
#
#       -  A configuraton service that uses a git-based repository to read the files from
#

#########################################

#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        git:
#          uri: https://github.com/ernestoacosta75/config-repo.git
#          searchPaths: licensingservice,organizationservice
#          username: ernestoacosta75
#          password: Cbcoa1975

####
#Classpath and file based-solution
####

server:
  port: 8888    # Port the Spring Cloud configuration server will listen to
spring:
  profiles:
    active: native  # The backend repository(filesystem) that will be used to store the configuration. It's native because we're using the filesystem for storing application configuration information      
  cloud:
    config:
      server:
        native:
           # The path to where the configuration files are stored
          searchLocations: file:///home/ernestoacostacuba/Documenti/Corsi/SpringBoot-Microservices/configurationserver/src/main/resources/config/licensingservice
          